# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# We need to create a function that request the range for the Fubonacci sequence.
def fib_even_sum(loop_range):
    #definec or assign two values a and b with 1 and 2 for strating point.
    a = 1
    b = 2
    #Place to store sum of the even-valued terms in fibonacci and the next fibonacci sequence num. Keep next_num as 2 as we started with 1 and 2 and 2 is an even value we dont wont to miss.
    sum = 2
    next_num = 0
    #Create a loop where we can store the even valued sum.
    while b < loop_range:
        #Create a fibonacci sequence by adding the firt and second number.
        #Replace the value of first by second and second by the next number.
        next_num = a + b
        a = b
        b = next_num
        # print(next_num)
        if((next_num % 2) == 0):
            sum += next_num

    return sum


print(fib_even_sum(4000000))
